FROM ubuntu:26.04

RUN apt update && apt install -y \
    build-essential \
    git \
    gunicorn \
    python3 \
    python3-dev \
    python3-pip \
    python3-venv \
    && ln -s /usr/bin/python3 /usr/bin/python \
    && apt clean

COPY requirements.txt /app/requirements.txt
ENV BLIS_ARCH="generic"
RUN pip install --break-system-packages blis --no-binary blis
RUN pip install --break-system-packages -r /app/requirements.txt
COPY . /app/

WORKDIR /app

ENTRYPOINT [ "flask", "--app", "websocket.server", "run", "--host=0.0.0.0", "--port=5001"]
